const types = {
  REGISTER_TRANSACTIONS: "@creditCard/REGISTER_TRANSACTIONS",
  SET_TRANSACTIONS: "@creditCard/SET_TRANSACTIONS", 
  GET_TRANSACTIONS: "@creditCard/GET_TRANSACTIONS",
  GET_TRANSACTIONS_RELEASE: "@creditCard/GET_TRANSACTIONS_RELEASE",
  SET_TRANSACTIONS_RELEASE: "@creditCard/SET_TRANSACTIONS_RELEASE",
  GET_SHOW_TRANSACTIONS: "@creditCard/GET_SHOW_TRANSACTIONS",    
  SET_SHOW_TRANSACTIONS: "@creditCard/SET_SHOW_TRANSACTIONS",
  UPDATE_TRANSACTION: "@creditCard/UPDATE_TRANSACTION", 
  DELETE_TRANSACTION: "@creditCard/DELETE_TRANSACTION",
}
export default types