const types = {
  REGISTER_TRANSACTIONS: "@creditCard/REGISTER_TRANSACTIONS",
  SET_TRANSACTIONS: "@creditCard/SET_TRANSACTIONS", 
  GET_TRANSACTIONS: "@creditCard/GET_TRANSACTIONS",
  GET_SHOW_TRANSACTIONS: "@creditCard/GET_SHOW_TRANSACTIONS",    
  SET_SHOW_TRANSACTIONS: "@creditCard/SET_SHOW_TRANSACTIONS", 
}

export default types